export const CreateTaskInput = {
  categoryId: 0,
  subCategoryId: 0,
  subSubCategoryId: 0,
  currentAssignee: 0,
  title: "",
  description: "",
  dueDate: "",
  lat: "",
  lon: "",
  refTaskId: 0,
  notes: "",
  fileIds: [],
  watcherIds: [],
  notes: "",
};
